palette = "catppuccin_mocha"

# Don't print a new line at the start of the prompt
add_newline = false

[character]
error_symbol = "[✖](bold red)"

[cmd_duration]
min_time = 1000
show_milliseconds = true
show_notifications = true
style = "underline white"

[directory]
truncation_length = 5

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
conflicted = "✘"
deleted = "✝"
format = '([\[$all_status$ahead_behind\]]($style) )'
staged = "✚"
stashed = "⚑"
style = "bold purple"

[time]
disabled = false
format = "$time($style) "
style = "dimmed"
time_format = "%Y-%m-%d %T"

[aws]
disabled = true

[docker_context]
disabled = true

[fennel]
format = "[$symbol ($version )]($style)"
symbol = ""
style= 'bold yellow'

[gcloud]
disabled = true

[lua]
format = "[$symbol ($version )]($style)"
symbol = ""

[nodejs]
disabled = true

[package]
disabled = true

[python]
format = '[${symbol} ${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
python_binary = ["./venv/bin/python", "python3", "python", "python2"]
symbol = ""
style= 'bold green'

[rlang]
format = "[$symbol ($version )]($style)"
symbol = "R"

[vagrant]
disabled = true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
